global using System.Net.Http.Json;
global using Microsoft.AspNetCore.Components;
global using Microsoft.AspNetCore.Components.WebAssembly.Hosting;
global using Microsoft.AspNetCore.Components.Web;
global using MudBlazor;
global using MudBlazor.Services;
global using BlazorDownloadFile;
global using FLLSlides.Pages;
global using FLLSlides.Shared;