# For more info on HTTP files go to https://aka.ms/vs/httpfile

@base = http://localhost:7071/api/GetTemplateDetails

# Get the template details
POST {{base}}
Accept: application/json

{
    "Name": "2023-05-10"
}